---
version: "2.1"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
#    cap_add:
#      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_MYSQL_HOST=${NPMDBHOST}
      - DB_MYSQL_PORT=${NPMDBPORT}
      - DB_MYSQL_USER=${NPMUSR}
      - DB_MYSQL_PASSWORD=${NPMPASS}
      - DB_MYSQL_NAME=${NPMDBNAME}
      - DISABLE_IPV6="true"
    volumes:
      - ${LOCVOL1}npm:/data
      - ${LOCVOL1}npm-certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
      - 10081:81
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    depends_on:
      - npm-db
#
  db:
    image: lscr.io/linuxserver/mariadb
    container_name: npm-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}npm-db:/config
#    ports:
#      - 3306:3306
    restart: unless-stopped
#
networks:
  default:
    external:
      name: ${CONNET}